"""Launcher shims and PATH wiring.

The installed commands are real executables in a directory on PATH, not shell
aliases. Aliases only exist inside interactive shells, so `ssh host
claude-switch usage`, cron jobs and scripts would all fail to find them.

Every shim resolves the active version through the `current` pointer at call
time, so an update takes effect immediately without rewriting any shim.
"""

import os
import sys

from .jsonio import write_text
from .term import dim, info, ok, warn

BEGIN = "# >>> cc-switch >>>"
END = "# <<< cc-switch <<<"

# Markers used before the repo was renamed. Still recognised when stripping, so
# a re-install replaces an old block instead of leaving a second, stale one
# behind that would keep putting a dead path on PATH.
LEGACY_MARKERS = (
    ("# >>> claude-code-multi-account-switch >>>",
     "# <<< claude-code-multi-account-switch <<<"),
)

_BEGINS = frozenset([BEGIN] + [b for b, _ in LEGACY_MARKERS])
_ENDS = frozenset([END] + [e for _, e in LEGACY_MARKERS])

# The subcommand each shim pins, so `claude-next` needs no arguments.
COMMANDS = (
    ("claude-switch", ""),
    ("claude-next", "next"),
    ("claude-usage", "usage"),
)

# Aliases written by v1/v2 init scripts. Stripped on install so they cannot
# shadow the shims with a path that no longer exists.
STALE_ALIASES = (
    "alias claude-switch=", "alias claude-next=",
    "alias claude-usage=", "alias claude-sync=",
)

POSIX_SHIM = """\
#!/usr/bin/env sh
# Generated by `claude-switch setup`. Edits here are overwritten.
ROOT='{root}'
if [ ! -f "$ROOT/current" ]; then
    echo "claude-switch: broken install at $ROOT - re-run the installer" >&2
    exit 1
fi
VERSION=$(cat "$ROOT/current")
exec "$ROOT/versions/$VERSION/bin/claude-switch.sh" {sub}"$@"
"""

WINDOWS_SHIM = """\
@echo off
rem Generated by `claude-switch setup`. Edits here are overwritten.
setlocal
set "ROOT={root}"
if not exist "%ROOT%\\current" (
    echo claude-switch: broken install at %ROOT% - re-run the installer 1>&2
    exit /b 1
)
set /p VERSION=<"%ROOT%\\current"
set "PYTHONIOENCODING=utf-8"
"{python}" "%ROOT%\\versions\\%VERSION%\\bin\\claude-accounts.py" {sub}%*
exit /b %ERRORLEVEL%
"""

PATH_BLOCK = """\
{begin}
# Managed by claude-switch. Do not edit; run `claude-switch setup` to rebuild.
case ":$PATH:" in
    *":{dir}:"*) ;;
    *) PATH="{dir}:$PATH" ;;
esac
export PATH
{end}
"""


# --------------------------------------------------------------------------
# locations
# --------------------------------------------------------------------------

def shim_dir(root: str) -> str:
    """Where the `claude-switch` executable itself lives.

    On Windows the shims sit inside the install root because there is no
    conventional per-user bin directory to drop them in.
    """
    override = os.environ.get("CLAUDE_SWITCH_BIN")
    if override:
        return os.path.abspath(os.path.expanduser(override))
    if os.name == "nt":
        return os.path.join(root, "bin")
    return os.path.join(os.path.expanduser("~"), ".local", "bin")


def rc_files():
    """Shell rc files that should get the PATH block."""
    home = os.path.expanduser("~")
    found = []
    for name in (".bashrc", ".zshrc"):
        path = os.path.join(home, name)
        if os.path.isfile(path):
            found.append(path)
    # macOS bash reads .bash_profile for login shells and often has no .bashrc.
    if sys.platform == "darwin":
        path = os.path.join(home, ".bash_profile")
        if os.path.isfile(path):
            found.append(path)

    if not found:
        shell = os.path.basename(os.environ.get("SHELL", "") or "")
        name = ".zshrc" if shell == "zsh" else ".bashrc"
        found.append(os.path.join(home, name))
    return found


# --------------------------------------------------------------------------
# shims
# --------------------------------------------------------------------------

def write_shims(root: str) -> str:
    """(Re)generate every launcher. Returns the directory they went into."""
    target = shim_dir(root)
    os.makedirs(target, exist_ok=True)

    for name, sub in COMMANDS:
        arg = f"{sub} " if sub else ""
        # Git Bash honours the shebang but will not append `.cmd`, while
        # cmd.exe and PowerShell will only run the `.cmd`. On Windows both are
        # written side by side so either shell finds a working launcher.
        posix = POSIX_SHIM.format(root=root.replace("\\", "/"), sub=arg)
        write_text(os.path.join(target, name), posix, executable=True)
        if os.name == "nt":
            windows = WINDOWS_SHIM.format(
                root=root, python=sys.executable, sub=arg)
            # cmd.exe mis-parses multi-line blocks in an LF-only batch file.
            write_text(os.path.join(target, name + ".cmd"),
                       windows.replace("\n", "\r\n"))

    return target


# --------------------------------------------------------------------------
# PATH
# --------------------------------------------------------------------------

def _strip_managed(text: str) -> str:
    """Drop our block and any stale aliases, so re-running stays idempotent."""
    kept, inside = [], False
    for line in text.splitlines(True):
        stripped = line.strip()
        if stripped in _BEGINS:
            inside = True
            continue
        if stripped in _ENDS:
            inside = False
            continue
        if inside or stripped.startswith(STALE_ALIASES):
            continue
        kept.append(line)

    while kept and not kept[-1].strip():
        kept.pop()
    return "".join(kept)


def _ensure_path_posix(directory: str):
    block = PATH_BLOCK.format(begin=BEGIN, end=END, dir=directory)
    touched = []
    for rc in rc_files():
        try:
            with open(rc, "r", encoding="utf-8", errors="replace") as fh:
                existing = _strip_managed(fh.read())
        except FileNotFoundError:
            existing = ""

        body = f"{existing}\n\n{block}" if existing else block
        try:
            write_text(rc, body)
        except OSError as exc:
            warn(f"could not update {rc}: {exc}")
            continue
        touched.append(rc)
    return touched


def _broadcast_env_change() -> None:
    """Tell running shells the user environment moved. Best effort."""
    try:
        import ctypes

        ctypes.windll.user32.SendMessageTimeoutW(
            0xFFFF, 0x001A, 0, ctypes.c_wchar_p("Environment"), 0, 1000, None)
    except Exception:
        pass


def _ensure_path_windows(directory: str) -> bool:
    """Prepend `directory` to the user PATH. True if it had to be added.

    Written to HKCU\\Environment rather than a PowerShell profile so cmd.exe,
    Git Bash and any GUI-launched terminal pick the commands up too.
    """
    import winreg

    want = os.path.normcase(os.path.normpath(directory))
    with winreg.OpenKey(winreg.HKEY_CURRENT_USER, "Environment", 0,
                        winreg.KEY_READ | winreg.KEY_WRITE) as key:
        try:
            current, kind = winreg.QueryValueEx(key, "Path")
        except OSError:
            current, kind = "", winreg.REG_EXPAND_SZ

        entries = [p for p in str(current).split(os.pathsep) if p]
        for entry in entries:
            if os.path.normcase(os.path.normpath(entry)) == want:
                return False

        winreg.SetValueEx(key, "Path", 0, kind or winreg.REG_EXPAND_SZ,
                          os.pathsep.join([directory] + entries))

    _broadcast_env_change()
    return True


def ensure_on_path(directory: str) -> None:
    """Make `directory` resolvable in future shells, reporting what changed."""
    on_path = any(
        os.path.normcase(os.path.normpath(p)) ==
        os.path.normcase(os.path.normpath(directory))
        for p in os.environ.get("PATH", "").split(os.pathsep) if p
    )

    if os.name == "nt":
        try:
            added = _ensure_path_windows(directory)
        except OSError as exc:
            warn(f"could not update your PATH: {exc}")
            warn(f"add this directory to PATH by hand: {directory}")
            return
        if added:
            ok(f"added {directory} to your PATH")
        elif on_path:
            info(f"{dim(directory)} already on PATH")
        return

    touched = _ensure_path_posix(directory)
    for rc in touched:
        ok(f"PATH configured in {rc}")
    if on_path:
        info(f"{dim(directory)} already on PATH for this shell")


def activation_hint():
    """How to make the commands usable in the shell that ran the installer."""
    if os.name == "nt":
        return ["open a new terminal (PATH changes do not reach this one)"]
    return [f"source {rc}" for rc in rc_files()] + ["(or open a new terminal)"]
